-- ============================================================
-- 02_create_tables.sql
-- Creates all 12 tables across 3 schemas
-- Mock data is NOT included here — use CoCo Prompt 2 to generate it,
-- or load from CSV files if provided.
-- ============================================================

USE DATABASE INSURANCE_AI_HUB;
USE WAREHOUSE AI_HUB_WH;

-- ============================================================
-- ANALYTICS SCHEMA
-- ============================================================
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(50),
    STATE VARCHAR(2),
    ZIP_CODE VARCHAR(10),
    RISK_TIER VARCHAR(20),
    CREDIT_SCORE NUMBER(38,0),
    CUSTOMER_SINCE DATE,
    SEGMENT VARCHAR(30),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE AGENTS (
    AGENT_ID VARCHAR(20) NOT NULL,
    AGENT_NAME VARCHAR(100),
    AGENT_TYPE VARCHAR(30),
    REGION VARCHAR(50),
    BRANCH VARCHAR(50),
    HIRE_DATE DATE,
    LICENSE_NUMBER VARCHAR(30),
    SPECIALIZATION VARCHAR(50),
    PERFORMANCE_RATING FLOAT,
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (AGENT_ID)
);

CREATE OR REPLACE TABLE POLICIES (
    POLICY_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(20),
    AGENT_ID VARCHAR(20),
    POLICY_TYPE VARCHAR(20),
    POLICY_STATUS VARCHAR(20),
    START_DATE DATE,
    END_DATE DATE,
    PREMIUM_AMOUNT NUMBER(12,2),
    COVERAGE_AMOUNT NUMBER(14,2),
    DEDUCTIBLE NUMBER(10,2),
    LOSS_RATIO FLOAT,
    PLAN_TIER VARCHAR(20),
    PAYMENT_FREQUENCY VARCHAR(20),
    AUTO_RENEW BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (POLICY_ID)
);

CREATE OR REPLACE TABLE CLAIMS (
    CLAIM_ID VARCHAR(20) NOT NULL,
    POLICY_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    CLAIM_DATE DATE,
    CLAIM_TYPE VARCHAR(30),
    CLAIM_STATUS VARCHAR(30),
    CLAIM_AMOUNT NUMBER(12,2),
    APPROVED_AMOUNT NUMBER(12,2),
    FRAUD_FLAG BOOLEAN DEFAULT FALSE,
    FRAUD_SCORE FLOAT,
    ASSIGNED_ADJUSTER VARCHAR(50),
    RESOLUTION_DATE DATE,
    DAYS_TO_RESOLVE NUMBER(38,0),
    FRICTION_POINT VARCHAR(100),
    PRIORITY VARCHAR(10),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLAIM_ID)
);

CREATE OR REPLACE TABLE BILLING (
    BILLING_ID VARCHAR(20) NOT NULL,
    POLICY_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    INVOICE_DATE DATE,
    DUE_DATE DATE,
    AMOUNT_DUE NUMBER(12,2),
    AMOUNT_PAID NUMBER(12,2),
    OUTSTANDING_BALANCE NUMBER(12,2),
    PAYMENT_STATUS VARCHAR(20),
    PAYMENT_METHOD VARCHAR(30),
    PAYMENT_DATE DATE,
    LATE_FEE NUMBER(8,2),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (BILLING_ID)
);

CREATE OR REPLACE TABLE AT_RISK_POLICIES (
    RISK_ID VARCHAR(20) NOT NULL,
    POLICY_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    RISK_CATEGORY VARCHAR(30),
    RISK_SCORE FLOAT,
    REVENUE_AT_RISK NUMBER(12,2),
    CHURN_PROBABILITY FLOAT,
    LAST_INTERACTION_DATE DATE,
    DAYS_SINCE_CONTACT NUMBER(38,0),
    COMPLAINTS_COUNT NUMBER(38,0),
    MISSED_PAYMENTS NUMBER(38,0),
    RECOMMENDED_ACTION VARCHAR(200),
    IDENTIFIED_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RISK_ID)
);

-- ============================================================
-- DOCUMENTS SCHEMA
-- ============================================================
USE SCHEMA DOCUMENTS;

CREATE OR REPLACE TABLE POLICY_DOCUMENTS (
    DOCUMENT_ID VARCHAR(20) NOT NULL,
    POLICY_ID VARCHAR(20),
    DOCUMENT_TYPE VARCHAR(50),
    DOCUMENT_TITLE VARCHAR(200),
    FILE_NAME VARCHAR(200),
    FILE_FORMAT VARCHAR(10),
    UPLOAD_DATE DATE,
    CONTENT_TEXT VARCHAR(16777216),
    EXCLUSION_CLAUSES VARCHAR(16777216),
    COVERAGE_SUMMARY VARCHAR(16777216),
    PAGE_COUNT NUMBER(38,0),
    DOCUMENT_STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DOCUMENT_ID)
);

CREATE OR REPLACE TABLE DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR(20) NOT NULL,
    DOCUMENT_ID VARCHAR(20),
    CHUNK_INDEX NUMBER(38,0),
    CHUNK_TEXT VARCHAR(16777216),
    SECTION_TITLE VARCHAR(200),
    TOKEN_COUNT NUMBER(38,0),
    EMBEDDING VECTOR(FLOAT, 768),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CHUNK_ID)
);

-- ============================================================
-- DATA_QUALITY SCHEMA
-- ============================================================
USE SCHEMA DATA_QUALITY;

CREATE OR REPLACE TABLE DQ_RULES (
    RULE_ID VARCHAR(20) NOT NULL,
    RULE_NAME VARCHAR(100),
    RULE_DESCRIPTION VARCHAR(500),
    TARGET_TABLE VARCHAR(100),
    TARGET_COLUMN VARCHAR(100),
    RULE_TYPE VARCHAR(30),
    RULE_EXPRESSION VARCHAR(500),
    SEVERITY VARCHAR(20),
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    THRESHOLD_PCT FLOAT,
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RULE_ID)
);

CREATE OR REPLACE TABLE DQ_RESULTS (
    RESULT_ID VARCHAR(20) NOT NULL,
    RULE_ID VARCHAR(20),
    EXECUTION_DATE TIMESTAMP_NTZ(9),
    TARGET_TABLE VARCHAR(100),
    TARGET_COLUMN VARCHAR(100),
    TOTAL_RECORDS NUMBER(38,0),
    PASSED_RECORDS NUMBER(38,0),
    FAILED_RECORDS NUMBER(38,0),
    PASS_RATE FLOAT,
    STATUS VARCHAR(20),
    ERROR_SAMPLE VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (RESULT_ID)
);

CREATE OR REPLACE TABLE DQ_SCORES (
    SCORE_ID VARCHAR(20) NOT NULL,
    TABLE_NAME VARCHAR(100),
    SCHEMA_NAME VARCHAR(100),
    SCORE_DATE DATE,
    OVERALL_SCORE FLOAT,
    COMPLETENESS_SCORE FLOAT,
    ACCURACY_SCORE FLOAT,
    CONSISTENCY_SCORE FLOAT,
    TIMELINESS_SCORE FLOAT,
    RULES_PASSED NUMBER(38,0),
    RULES_FAILED NUMBER(38,0),
    TOTAL_RULES NUMBER(38,0),
    TREND VARCHAR(10),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SCORE_ID)
);

CREATE OR REPLACE TABLE DQ_COLUMN_HEALTH (
    HEALTH_ID VARCHAR(20) NOT NULL,
    TABLE_NAME VARCHAR(100),
    COLUMN_NAME VARCHAR(100),
    CHECK_DATE DATE,
    NULL_PCT FLOAT,
    DISTINCT_COUNT NUMBER(38,0),
    DUPLICATE_PCT FLOAT,
    OUTLIER_COUNT NUMBER(38,0),
    FORMAT_VIOLATION_COUNT NUMBER(38,0),
    HEALTH_STATUS VARCHAR(20),
    SCORE FLOAT,
    IS_CRITICAL BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (HEALTH_ID)
);
