-- ============================================================
-- 03_create_semantic_view.sql
-- Creates the semantic view for Cortex Analyst
-- ============================================================

USE DATABASE INSURANCE_AI_HUB;
USE SCHEMA ANALYTICS;
USE WAREHOUSE AI_HUB_WH;

CREATE OR REPLACE SEMANTIC VIEW INSURANCE_SEMANTIC_MODEL
    TABLES (
        INSURANCE_AI_HUB.ANALYTICS.AGENTS PRIMARY KEY (AGENT_ID),
        INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES PRIMARY KEY (RISK_ID),
        INSURANCE_AI_HUB.ANALYTICS.BILLING PRIMARY KEY (BILLING_ID),
        INSURANCE_AI_HUB.ANALYTICS.CLAIMS PRIMARY KEY (CLAIM_ID),
        INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
        INSURANCE_AI_HUB.ANALYTICS.POLICIES PRIMARY KEY (POLICY_ID)
    )
    RELATIONSHIPS (
        AT_RISK_TO_POLICIES AS AT_RISK_POLICIES(POLICY_ID) REFERENCES POLICIES(POLICY_ID),
        BILLING_TO_POLICIES AS BILLING(POLICY_ID) REFERENCES POLICIES(POLICY_ID),
        CLAIMS_TO_CUSTOMERS AS CLAIMS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        CLAIMS_TO_POLICIES AS CLAIMS(POLICY_ID) REFERENCES POLICIES(POLICY_ID),
        POLICIES_TO_AGENTS AS POLICIES(AGENT_ID) REFERENCES AGENTS(AGENT_ID),
        POLICIES_TO_CUSTOMERS AS POLICIES(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
    )
    FACTS (
        AGENTS.PERFORMANCE_RATING AS PERFORMANCE_RATING,
        AT_RISK_POLICIES.CHURN_PROBABILITY AS CHURN_PROBABILITY WITH SYNONYMS=('chance of churn','likelihood to cancel'),
        AT_RISK_POLICIES.COMPLAINTS_COUNT AS COMPLAINTS_COUNT,
        AT_RISK_POLICIES.MISSED_PAYMENTS AS MISSED_PAYMENTS,
        AT_RISK_POLICIES.REVENUE_AT_RISK AS REVENUE_AT_RISK WITH SYNONYMS=('premium at risk'),
        AT_RISK_POLICIES.RISK_SCORE AS RISK_SCORE,
        BILLING.AMOUNT_DUE AS AMOUNT_DUE,
        BILLING.AMOUNT_PAID AS AMOUNT_PAID,
        BILLING.LATE_FEE AS LATE_FEE,
        BILLING.OUTSTANDING_BALANCE AS OUTSTANDING_BALANCE WITH SYNONYMS=('balance owed','unpaid amount'),
        CLAIMS.APPROVED_AMOUNT AS APPROVED_AMOUNT WITH SYNONYMS=('amount paid','payout'),
        CLAIMS.CLAIM_AMOUNT AS CLAIM_AMOUNT WITH SYNONYMS=('amount claimed'),
        CLAIMS.CLAIM_DATE AS CLAIM_DATE,
        CLAIMS.DAYS_TO_RESOLVE AS DAYS_TO_RESOLVE WITH SYNONYMS=('resolution time','turnaround time'),
        CLAIMS.FRAUD_SCORE AS FRAUD_SCORE WITH SYNONYMS=('risk score'),
        CUSTOMERS.CREDIT_SCORE AS CREDIT_SCORE,
        CUSTOMERS.CUSTOMER_SINCE AS CUSTOMER_SINCE,
        POLICIES.COVERAGE_AMOUNT AS COVERAGE_AMOUNT WITH SYNONYMS=('coverage','sum insured'),
        POLICIES.DEDUCTIBLE AS DEDUCTIBLE,
        POLICIES.END_DATE AS END_DATE,
        POLICIES.LOSS_RATIO AS LOSS_RATIO WITH SYNONYMS=('claims to premium ratio','loss ratio percentage'),
        POLICIES.PREMIUM_AMOUNT AS PREMIUM_AMOUNT WITH SYNONYMS=('premium','premium cost'),
        POLICIES.START_DATE AS START_DATE
    )
    DIMENSIONS (
        AGENTS.AGENT_NAME AS AGENT_NAME,
        AGENTS.AGENT_TYPE AS AGENT_TYPE WITH SYNONYMS=('job type','role'),
        AGENTS.BRANCH AS BRANCH,
        AGENTS.REGION AS REGION,
        AGENTS.SPECIALIZATION AS SPECIALIZATION,
        AT_RISK_POLICIES.RECOMMENDED_ACTION AS RECOMMENDED_ACTION,
        AT_RISK_POLICIES.RISK_CATEGORY AS RISK_CATEGORY WITH SYNONYMS=('reason at risk'),
        BILLING.PAYMENT_METHOD AS PAYMENT_METHOD,
        BILLING.PAYMENT_STATUS AS PAYMENT_STATUS WITH SYNONYMS=('status'),
        CLAIMS.ASSIGNED_ADJUSTER AS ASSIGNED_ADJUSTER,
        CLAIMS.CLAIM_STATUS AS CLAIM_STATUS WITH SYNONYMS=('status'),
        CLAIMS.CLAIM_TYPE AS CLAIM_TYPE WITH SYNONYMS=('type of claim'),
        CLAIMS.FRAUD_FLAG AS FRAUD_FLAG WITH SYNONYMS=('flagged as fraud','suspicious'),
        CLAIMS.FRICTION_POINT AS FRICTION_POINT WITH SYNONYMS=('bottleneck','delay reason'),
        CLAIMS.PRIORITY AS PRIORITY,
        CUSTOMERS.CITY AS CITY,
        CUSTOMERS.GENDER AS GENDER,
        CUSTOMERS.RISK_TIER AS RISK_TIER WITH SYNONYMS=('risk category','risk level'),
        CUSTOMERS.SEGMENT AS SEGMENT WITH SYNONYMS=('customer segment','customer type'),
        CUSTOMERS.STATE AS STATE,
        POLICIES.PAYMENT_FREQUENCY AS PAYMENT_FREQUENCY,
        POLICIES.PLAN_TIER AS PLAN_TIER WITH SYNONYMS=('plan level','tier'),
        POLICIES.POLICY_STATUS AS POLICY_STATUS WITH SYNONYMS=('status'),
        POLICIES.POLICY_TYPE AS POLICY_TYPE WITH SYNONYMS=('coverage type','product','type of policy')
    )
    METRICS (
        AT_RISK_POLICIES.TOTAL_REVENUE_AT_RISK AS SUM(REVENUE_AT_RISK),
        BILLING.TOTAL_OUTSTANDING AS SUM(OUTSTANDING_BALANCE) WITH SYNONYMS=('total amount owed','total unpaid'),
        CLAIMS.AVG_FRAUD_SCORE AS AVG(FRAUD_SCORE),
        CLAIMS.AVG_RESOLUTION_DAYS AS AVG(DAYS_TO_RESOLVE) WITH SYNONYMS=('average turnaround'),
        CLAIMS.FRAUD_FLAGGED_COUNT AS COUNT_IF(FRAUD_FLAG = TRUE) WITH SYNONYMS=('number of fraud cases'),
        CLAIMS.TOTAL_CLAIMS_PAID AS SUM(APPROVED_AMOUNT) WITH SYNONYMS=('total claims cost','total payouts'),
        POLICIES.ACTIVE_POLICY_COUNT AS COUNT_IF(POLICY_STATUS = 'Active') WITH SYNONYMS=('number of active policies'),
        POLICIES.AVG_LOSS_RATIO AS AVG(LOSS_RATIO) WITH SYNONYMS=('average loss ratio'),
        POLICIES.TOTAL_PREMIUM AS SUM(PREMIUM_AMOUNT) WITH SYNONYMS=('total premium collected','total revenue')
    )
    COMMENT = 'Semantic model for insurance policies, claims, billing, agents, and customer risk';
