-- ============================================================
-- 07_load_data.sql
-- Loads mock data from CSV files into all 12 tables
-- Prerequisites:
--   1. Run 01_setup_database.sql and 02_create_tables.sql first
--   2. Upload CSV files from data/ folder to the DATA_STAGE:
--      PUT 'file:///path/to/data/*.csv' @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/ AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- ============================================================

USE DATABASE INSURANCE_AI_HUB;
USE WAREHOUSE AI_HUB_WH;

-- Create a stage + file format for data loading
CREATE STAGE IF NOT EXISTS INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE;

CREATE FILE FORMAT IF NOT EXISTS INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('');

-- ============================================================
-- ANALYTICS SCHEMA
-- ============================================================
USE SCHEMA ANALYTICS;

COPY INTO CUSTOMERS FROM @DATA_STAGE/customers.csv FILE_FORMAT = CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO AGENTS FROM @DATA_STAGE/agents.csv FILE_FORMAT = CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO POLICIES FROM @DATA_STAGE/policies.csv FILE_FORMAT = CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO CLAIMS FROM @DATA_STAGE/claims.csv FILE_FORMAT = CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO BILLING FROM @DATA_STAGE/billing.csv FILE_FORMAT = CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO AT_RISK_POLICIES FROM @DATA_STAGE/at_risk_policies.csv FILE_FORMAT = CSV_LOAD ON_ERROR = 'CONTINUE';

-- ============================================================
-- DOCUMENTS SCHEMA
-- ============================================================
USE SCHEMA DOCUMENTS;

COPY INTO POLICY_DOCUMENTS FROM @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/policy_documents.csv FILE_FORMAT = INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO DOCUMENT_CHUNKS (CHUNK_ID, DOCUMENT_ID, CHUNK_INDEX, CHUNK_TEXT, SECTION_TITLE, TOKEN_COUNT, CREATED_AT)
    FROM @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/document_chunks.csv FILE_FORMAT = INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD ON_ERROR = 'CONTINUE';

-- ============================================================
-- DATA_QUALITY SCHEMA
-- ============================================================
USE SCHEMA DATA_QUALITY;

COPY INTO DQ_RULES FROM @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/dq_rules.csv FILE_FORMAT = INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO DQ_RESULTS FROM @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/dq_results.csv FILE_FORMAT = INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO DQ_SCORES FROM @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/dq_scores.csv FILE_FORMAT = INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD ON_ERROR = 'CONTINUE';
COPY INTO DQ_COLUMN_HEALTH FROM @INSURANCE_AI_HUB.ANALYTICS.DATA_STAGE/dq_column_health.csv FILE_FORMAT = INSURANCE_AI_HUB.ANALYTICS.CSV_LOAD ON_ERROR = 'CONTINUE';

-- ============================================================
-- VERIFY COUNTS
-- ============================================================
SELECT 'CUSTOMERS' AS tbl, COUNT(*) AS cnt FROM INSURANCE_AI_HUB.ANALYTICS.CUSTOMERS
UNION ALL SELECT 'AGENTS', COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.AGENTS
UNION ALL SELECT 'POLICIES', COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.POLICIES
UNION ALL SELECT 'CLAIMS', COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.CLAIMS
UNION ALL SELECT 'BILLING', COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.BILLING
UNION ALL SELECT 'AT_RISK_POLICIES', COUNT(*) FROM INSURANCE_AI_HUB.ANALYTICS.AT_RISK_POLICIES
UNION ALL SELECT 'POLICY_DOCUMENTS', COUNT(*) FROM INSURANCE_AI_HUB.DOCUMENTS.POLICY_DOCUMENTS
UNION ALL SELECT 'DOCUMENT_CHUNKS', COUNT(*) FROM INSURANCE_AI_HUB.DOCUMENTS.DOCUMENT_CHUNKS
UNION ALL SELECT 'DQ_RULES', COUNT(*) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RULES
UNION ALL SELECT 'DQ_RESULTS', COUNT(*) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_RESULTS
UNION ALL SELECT 'DQ_SCORES', COUNT(*) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_SCORES
UNION ALL SELECT 'DQ_COLUMN_HEALTH', COUNT(*) FROM INSURANCE_AI_HUB.DATA_QUALITY.DQ_COLUMN_HEALTH
ORDER BY 1;
